#!/usr/bin/env ruby
require "phonto"

def help
  puts "training"
  puts "  $ #{$0} prepare PHOTO_DIR ILLUST_DIR [MODEL_DIR]"
  puts "classification"
  puts "  $ #{$0} run IMAGE_FILE [MODEL_DIR]"
  exit 1
end

help if ARGV.length < 1
case ARGV[0]
when 'prepare'
  help unless ARGV.length == 3 || ARGV.length == 4
  c = Phonto::CLI.new(ARGV[3] || './model')
  exit c.train(ARGV[1], ARGV[2])
when 'run'
  help unless ARGV.length == 2 || ARGV.length == 3
  c = Phonto::CLI.new(ARGV[2] || './model')
  exit c.classify(ARGV[1])
else
  help
end
